name: build
on:
  workflow_dispatch:

jobs:
  push:
    name: "friendconnect:${{ matrix.pattern }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./Container Image
          file: ./Container Image/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/ree-jp/friendconnect:egg

      - uses: docker/build-push-action@v4
        with:
          context: ./Installer Image
          file: ./Installer Image/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/ree-jp/friendconnect:yolks
